# Python Programming Advance Assignment-23


## 1. Create a class `Sudoku` that takes a string as an argument. The string will contain the numbers of a regular 9x9 sudoku board left to right and top to bottom, with zeros filling up the empty cells.

Attributes

An instance of the class `Sudoku` will have one attribute:

- `board`: a list representing the board, with sublist for each row, with the numbers as integers. Empty cell represented with 0.

Methods

An instance of the class Sudoku wil have three methods:

- `get_row(n)`: will return the row in position `n`.
- `get_col(n)`: will return the column in position `n`.
- `get_sqr([n, m])`: will return the square in position `n` if only one argument is given, and the square to which the cell in position `(n, m)` belongs to if two arguments are given.

Example  
![Sudoku](./a23-1.png)

```py
game = Sudoku("417950030000000700060007000050009106800600000000003400900005000000430000200701580")


game.board ➞ [
  [4, 1, 7, 9, 5, 0, 0, 3, 0],
  [0, 0, 0, 0, 0, 0, 7, 0, 0],
  [0, 6, 0, 0, 0, 7, 0, 0, 0],
  [0, 5, 0, 0, 0, 9, 1, 0, 6],
  [8, 0, 0, 6, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 3, 4, 0, 0],
  [9, 0, 0, 0, 0, 5, 0, 0, 0],
  [0, 0, 0, 4, 3, 0, 0, 0, 0],
  [2, 0, 0, 7, 0, 1, 5, 8, 0]
]

game.get_row(0) ➞ [4, 1, 7, 9, 5, 0, 0, 3, 0]
game.get_col(8) ➞ [0, 0, 0, 6, 0, 0, 0, 0, 0]
game.get_sqr(1) ➞ [9, 5, 0, 0, 0, 0, 0, 0, 7]
game.get_sqr(1, 8) ➞ [0, 3, 0, 7, 0, 0, 0, 0, 0]
game.get_sqr(8, 3) ➞ [0, 0, 5, 4, 3, 0, 7, 0, 1]
```


In [32]:
import numpy as np


class Sudoku:
    def __init__(self, board_nums: str):
        self.board = np.array([int(i) for i in board_nums]).reshape(9, 9)

    def get_row(self, n: int):
        return self.board[n]

    def get_col(self, n: int):
        return self.board[:, n]

    def get_sqr(self, n: int, m: int = None):
        if not m:
            return self.board[n // 3 * 3 : n // 3 * 3 + 3, n % 3 * 3 : n % 3 * 3 + 3].flatten()
        return self.board[n // 3 * 3 : n // 3 * 3 + 3, m // 3 * 3 : m // 3 * 3 + 3].flatten()


game = Sudoku("417950030000000700060007000050009106800600000000003400900005000000430000200701580")
game.board


array([[4, 1, 7, 9, 5, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 6, 0, 0, 0, 7, 0, 0, 0],
       [0, 5, 0, 0, 0, 9, 1, 0, 6],
       [8, 0, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 4, 0, 0],
       [9, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 4, 3, 0, 0, 0, 0],
       [2, 0, 0, 7, 0, 1, 5, 8, 0]])

In [33]:
game.get_row(0), game.get_col(8), game.get_sqr(1), game.get_sqr(1, 8), game.get_sqr(8, 3)


(array([4, 1, 7, 9, 5, 0, 0, 3, 0]),
 array([0, 0, 0, 6, 0, 0, 0, 0, 0]),
 array([9, 5, 0, 0, 0, 0, 0, 0, 7]),
 array([0, 3, 0, 7, 0, 0, 0, 0, 0]),
 array([0, 0, 5, 4, 3, 0, 7, 0, 1]))

## 2. The function input is two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list, in which the digits are also stored in reversed order. The class `ListNode`, building block of the linked list, is defined in the Tests tab.

Class definition

```py
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
```

Examples

```py
lt1 = ListNode(2)
lt1.add_data([4, 3])
lt2 = ListNode(5)
lt2.add_data([6, 4])
# print(lt1.get_data())    # [2, 4, 3]
# print(lt2.get_data())    # [5, 6, 4]
# print(342 + 465)         # 807
add_two_numbers(lt1, lt2).get_data() ➞ [7, 0, 8]

lt1 = ListNode(0)
lt2 = ListNode(0)
# print(lt1.get_data())    # [0]
# print(lt2.get_data())    # [0]
# print(0 + 0)             # 0
add_two_numbers(lt1, lt2).get_data() ➞ [0]

lt1 = ListNode(9)
lt1.add_data([9,9,9,9,9,9])
lt2 = ListNode(9)
lt2.add_data([9,9,9])
# print(lt1.get_data())    # [9, 9, 9, 9, 9, 9, 9]
# print(lt2.get_data())    # [9, 9, 9, 9]
# print(9999999 + 9999)    # 10009998
add_two_numbers(lt1, lt2).get_data() ➞ [8, 9, 9, 9, 0, 0, 0, 1]
```


In [34]:
class Node:
    def __init__(self, val: int = 0, next=None):
        self.val = val
        self.next = next


class ListNode:
    def __init__(self, head):
        self.head = Node(head)

    def add_data(self, node_datas):
        for node_data in node_datas:
            temp_node = Node(node_data)
            if not self.head:
                self.head = temp_node
                return
            last_node = self.head
            while last_node.next:
                last_node = last_node.next
            last_node.next = temp_node

    def get_data(self):
        res = []
        last_node = self.head
        res.append(last_node.val)
        while last_node.next:
            last_node = last_node.next
            res.append(last_node.val)
        return res


def add_two_numbers(node_1: ListNode, node_2: ListNode):
    one_data = "".join([str(i) for i in node_1.get_data()])[::-1]
    two_data = "".join([str(i) for i in node_2.get_data()])[::-1]
    res = int(one_data) + int(two_data)
    res = [int(i) for i in str(res)[::-1]]
    return res


In [35]:
lt1 = ListNode(2)
lt1.add_data([4, 3])
lt2 = ListNode(5)
lt2.add_data([6, 4])
lt1.get_data(), lt2.get_data(), add_two_numbers(lt1, lt2)


([2, 4, 3], [5, 6, 4], [7, 0, 8])

In [36]:
lt1 = ListNode(0)
lt2 = ListNode(0)
lt1.get_data(), lt2.get_data(), add_two_numbers(lt1, lt2)


([0], [0], [0])

In [37]:
lt1 = ListNode(9)
lt1.add_data([9, 9, 9, 9, 9, 9])
lt2 = ListNode(9)
lt2.add_data([9, 9, 9])
lt1.get_data(), lt2.get_data(), add_two_numbers(lt1, lt2)


([9, 9, 9, 9, 9, 9, 9], [9, 9, 9, 9], [8, 9, 9, 9, 0, 0, 0, 1])

## 3. Write a class called `CoffeeShop`, which has three instance variables:

1.  `name`: a string (basically, of the shop)
2.  `menu`: a list of items (of dict type), with each item containing the item (name of the item), type (whether a food or a drink) and price.
3.  `orders`: an empty list

and seven `methods`:

1. `add_order`: adds the name of the item to the end of the orders list if it exists on the menu, otherwise, return "This item is currently unavailable!"
2. `fulfill_order`: if the orders list is not empty, return "The {item} is ready!". If the orders list is empty, return "All orders have been fulfilled!"
3. `list_orders`: returns the item names of the orders taken, otherwise, an empty list.
4. `due_amount`: returns the total amount due for the orders taken.
5. `cheapest_item`: returns the name of the cheapest item on the menu.
6. `drinks_only`: returns only the item names of type drink from the menu.
7. `food_only`: returns only the item names of type food from the menu.

IMPORTANT: Orders are fulfilled in a `FIFO` (first-in, first-out) order.

Examples

```py
tcs.add_order("hot cocoa") ➞ "This item is currently unavailable!"
# Tesha's coffee shop does not sell hot cocoa
tcs.add_order("iced tea") ➞ "This item is currently unavailable!"
# specifying the variant of "iced tea" will help the process

tcs.add_order("cinnamon roll") ➞  "Order added!"
tcs.add_order("iced coffee") ➞ "Order added!"
tcs.list_orders ➞ ["cinnamon roll", "iced coffee"]
# all items of the current order

tcs.due_amount() ➞ 2.17

tcs.fulfill_order() ➞ "The cinnamon roll is ready!"
tcs.fulfill_order() ➞ "The iced coffee is ready!"
tcs.fulfill_order() ➞ "All orders have been fulfilled!"
# all orders have been presumably served

tcs.list_orders() ➞ []
# an empty list is returned if all orders have been exhausted

tcs.due_amount() ➞ 0.0
# no new orders taken, expect a zero payable

tcs.cheapest_item() ➞ "lemonade"
tcs.drinks_only() ➞ ["orange juice", "lemonade", "cranberry juice", "pineapple juice", "lemon iced tea", "vanilla chai latte", "hot chocolate", "iced coffee"]
tcs.food_only() ➞ ["tuna sandwich", "ham and cheese sandwich", "bacon and egg", "steak", "hamburger", "cinnamon roll"]
```


In [38]:
class CoffeeShop:
    def __init__(self, name: str, menu: list, orders: list = []):
        self.name = name
        self.menu = menu
        self.orders = orders

    def add_order(self, order: str):
        avail = [elem["name"].lower() for elem in self.menu]
        if order.lower() not in avail:
            return "This item is currently unavailable"
        self.orders.append(order.lower())
        return "Order added!"

    def fulfill_order(self):
        if self.orders:
            return f"The {self.orders.pop(0)} is ready!"
        return "All orders have been fulfilled!"

    def list_orders(self):
        return self.orders

    def due_amount(self):
        return sum([elem["price"] for elem in self.menu if elem["name"].lower() in self.orders])

    def cheapest_item(self):
        return min(self.menu, key=lambda x: x["price"])["name"]

    def drinks_only(self):
        return [elem["name"] for elem in self.menu if elem["type"] == "drink"]

    def foods_only(self):
        return [elem["name"] for elem in self.menu if elem["type"] == "food"]


In [39]:
MENU = [
    {"name": "Orange Juice", "type": "drink", "price": 25.50},
    {"name": "Lemonade", "type": "drink", "price": 10},
    {"name": "Cranberry Juice", "type": "drink", "price": 40},
    {"name": "Pineapple Juice", "type": "drink", "price": 40},
    {"name": "Lemon Iced Tea", "type": "drink", "price": 80},
    {"name": "Vanilla Chai Latte", "type": "drink", "price": 90},
    {"name": "Hot Chocolate", "type": "drink", "price": 100},
    {"name": "Iced Coffee", "type": "drink", "price": 70.12},
    {"name": "Tuna Sandwich", "type": "food", "price": 120},
    {"name": "Ham Cheese Sandwich", "type": "food", "price": 180},
    {"name": "Bacon And Egg", "type": "food", "price": 120},
    {"name": "Chicken Biryani", "type": "food", "price": 360},
    {"name": "Veg Burger", "type": "food", "price": 90},
    {"name": "Cinnamon Roll", "type": "food", "price": 60.25},
]
tcs = CoffeeShop("TCS", MENU)
tcs.add_order("hot cocoa"), tcs.add_order("iced tea"), tcs.add_order("cinnamon roll"), tcs.add_order("iced coffee")


('This item is currently unavailable',
 'This item is currently unavailable',
 'Order added!',
 'Order added!')

In [40]:
tcs.list_orders(), tcs.due_amount()


(['cinnamon roll', 'iced coffee'], 130.37)

In [41]:
tcs.fulfill_order(), tcs.fulfill_order(), tcs.fulfill_order(), tcs.list_orders(), tcs.due_amount()


('The cinnamon roll is ready!',
 'The iced coffee is ready!',
 'All orders have been fulfilled!',
 [],
 0)

In [42]:
tcs.cheapest_item(), tcs.drinks_only(), tcs.foods_only()


('Lemonade',
 ['Orange Juice',
  'Lemonade',
  'Cranberry Juice',
  'Pineapple Juice',
  'Lemon Iced Tea',
  'Vanilla Chai Latte',
  'Hot Chocolate',
  'Iced Coffee'],
 ['Tuna Sandwich',
  'Ham Cheese Sandwich',
  'Bacon And Egg',
  'Chicken Biryani',
  'Veg Burger',
  'Cinnamon Roll'])

## 4. In this challenge, write a function `loneliest_number` to find the last Lonely number inside a sequence. A number is Lonely if the distance from its closest Prime sets a new record of the sequence.

```
Sequence = from 0 to 3

# Any number lower than 3 doesn't have a Prime preceeding it...
# ...so that you'll consider only its next closest Prime.

0 has distance 2 from its closest Prime (2)
# It's a new record! 0 It's the first lonely number of the sequence
1 has distance 1 from its closest Prime (2)
2 has distance 1 from 3
3 has distance 1 from 2

# The sequence 0 to 3  has only one Lonely number: 0

Sequence = Numbers from 5 to 10

5 has distance 2 from its closest Prime (3 or 7)
# It's a new record! 5 It's the first lonely number of the sequence
6 has distance 1 from 5 or 7
7 has distance 2 from 5
8 has distance 1 from 7
9 has distance 2 from 7 or 11
10 has distance 1 from 11

# The sequence 5 to 10  has only one Lonely number: 5

Sequence = Numbers from 19 to 24

19 has distance 2 from its closest Prime (17)
# It's a new record! 19 It's the first lonely number of the sequence
20 has distance 1 from 19
21 has distance 2 from 5
22 has distance 1 from 23
23 has distance 4 from 17 or 29
# It's a new record! 23 is the second lonely number of the sequence
24 has distance 1 from 23

# The sequence 19 to 24  has two Lonely numbers: 19 and 23
```

The function loneliest_number must accept two integers lo and hi being the inclusive bounds of the sequence to analyze, and returns a dictionay (dict) object with the following keys and values:

- number: is the last Lonely number found in the given sequence;
- distance: is the distance of the number from its closest Prime;
- closest: is the Prime closest to number (if two Primes are equally distant from number, return the higher Prime).

Examples

```py
loneliest_number(0, 22) ➞ {
  number: 0, distance: 2, closest: 2
}

loneliest_number(8, 123) ➞ {
  number: 53, distance: 6, closest: 59
}

loneliest_number(938, 1190) ➞ {
  number: 1140, distance: 11, closest: 1151
}

loneliest_number(120, 1190) ➞ {
  number: 211, distance: 12, closest: 223
}
```


In [9]:
def gen_primes():
    n = 2
    primes = set()
    while True:
        for p in primes:
            if n % p == 0:
                break
        else:
            primes.add(n)
            yield n
        n += 1


In [34]:
def loneliest_number(start: int, end: int):
    prime_list = []
    output = {"number": 0, "distance": 0, "closest": 0}
    prev_prime = None
    for x in gen_primes():
        if x < start:
            prev_prime = x
        if x >= start:
            prime_list.append(x)
        if x > end:
            prime_list.insert(0, prev_prime) if prev_prime else None
            break
    temp = []
    for ele in range(start, end):
        org_ele = ele
        while True:
            if ele in prime_list:
                n_f_prime = ele if ele != org_ele else prime_list[prime_list.index(ele) + 1]
                n_b_prime = prime_list[prime_list.index(ele) - 1] if prime_list.index(ele) > 0 else 0
                closest_distance = (
                    min(org_ele - n_b_prime, n_f_prime - org_ele) if n_b_prime != 0 else n_f_prime - org_ele
                )
                closest_prime = n_f_prime if n_b_prime == 0 or closest_distance == n_f_prime - org_ele else n_b_prime
                temp.append(closest_distance)
                if output["distance"] < closest_distance:
                    output = {"number": org_ele, "distance": closest_distance, "closest": closest_prime}
                break
            else:
                ele += 1
    # print(temp)
    return output


loneliest_number(0, 22), loneliest_number(8, 123), loneliest_number(938, 1190), loneliest_number(120, 1190)
# in  8, 123 120 is the last loneliest number found hence answer is 120


({'number': 0, 'distance': 2, 'closest': 2},
 {'number': 120, 'distance': 7, 'closest': 127},
 {'number': 1140, 'distance': 11, 'closest': 1151},
 {'number': 211, 'distance': 12, 'closest': 223})

## 5. Implement a class `Selfie` that can store the current state of the object in the form of binary string. It can take multiple pictures and then recover to a state it was before. During testing an object will be provided with new attributes and their values. It will store its state. Then the values will be changed. Then it will be given new attributes. It will store its state again. It will be repeated few times.

Later the states of the object will be recovered given an index. The return value should be a new Selfie with the requested historic state and the state history of the new object should be updated with a copy of current object's state history.

The object also knows how many states it has stored. If the index is not within the range of stored states, the object stays as is. If the argument is invalid, `n < 0` or `n >= self.n_states()`, the current object (or a copy thereof) should be returned.

Examples

```py
p = Selfie()
p.x = 2
p.save_state()
p.x = 5
p = p.recover_state(0)
p.x ➞ 2
```


In [ ]:
class Selfie:
    def __init__(self, state=None):
        self.x = state
        self.__history = []

    def n_states(self):
        return len(self.__history)

    def save_state(self):
        self.__history.append(self.x)

    def recover_state(self, index: int):
        if not (index < 0 or index >= self.n_states()):
            self.x = self.__history[index]
        return self


p = Selfie()
p.x = 2
p.save_state()
p.x = 5
p = p.recover_state(0)
p.x


2