# Python Programming Basic Assignment-08


In [1]:
import numpy as np


## 1. Write a Python Program to Add Two Matrices?


In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
arr1, arr2


(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]))

In [12]:
arr1 + arr2


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## 2. Write a Python Program to Multiply Two Matrices?


In [22]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
arr1, arr2


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [21]:
arr1 @ arr2


array([[22, 28],
       [49, 64]])

In [23]:
arr2 @ arr1


array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

## 3. Write a Python Program to Transpose a Matrix?


In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(f"Array:\n{arr}\nTranspose of Array:\n{arr.T}")



Array:[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Transpose of Array:
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


## 4. Write a Python Program to Sort Words in Alphabetic Order?


In [31]:
string = "Good Morning is greeted when it's morning"
print(sorted([x.lower() for x in string.split(" ")]))


['good', 'greeted', 'is', "it's", 'morning', 'morning', 'when']


## 5. Write a Python Program to Remove Punctuation From a String?


Method 1


In [36]:
from string import punctuation

punctuation


'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [37]:
string2 = "Hello! James, nice to meet you."
string2


'Hello! James, nice to meet you.'

In [38]:
"".join([char for char in string2 if char not in punctuation])


'Hello James nice to meet you'

Method 2


In [39]:
import re


In [40]:
re.sub(r"[^\w\s]", "", string2)


'Hello James nice to meet you'

Method 3


In [41]:
string2.translate(str.maketrans("", "", punctuation))


'Hello James nice to meet you'